### ISSUE TITLE
tested image recognition

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#13]
We have tested with philip in bari the eagle app. we took a photo of a very common inscription, a milestone, expecting the similarity search to get some milestones at least, it that exact one was not there. The results returned are in fact extremely far from being relevant in any way. I suggest to test with philip image took in bari and try to understand what is going on.

**Comment by cprando** [comment]
The issue here is that the image recognition algorithm has a very low tolerance threshold, i.e. it returns also images that are very far from the original one. This was done on purpose in order to be able to test the algorithm. As soon as we have tested it we will increase the threshold in order to return only "similar" results, if any.

**Comment by cprando** [comment]
Fixed
